# https://fredrikaverpil.github.io/2016/07/31/docker-for-mac-and-gui-applications/
# http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
# http://wolfsrudel.biz/2016/03/xencenter-for-mac/
# https://github.com/OpenXenManager/openxenmanager
version: '3.2'
services:
  openxenmanager:
    # docker run --rm -d --name firefox -e DISPLAY=$(ipconfig getifaddr en0):0 -v /tmp/.X11-unix:/tmp/.X11-unix jess/firefox
    build: ./docker
    container_name: openxenmanager
    environment:
      - DISPLAY=192.168.1.52:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ./mnt/root/.local/share:/root/.local/share
      - ./mnt/root/.config/openxenmanager:/root/.config/openxenmanager
